import type { PeriodReport } from './period-report';
export function reportCsv(reports:PeriodReport[],details=false){
  const branches=[...new Map(reports.flatMap(r=>r.summary.branches.map(b=>[b.id,b.name] as const))).entries()];
  const rows:unknown[][]=details?
    [['الموظف','اسم الدخول','التاريخ','الحالة','بداية الشيفت','نهاية الشيفت','أول وصول','آخر انصراف','داخل الفروع حسب GPS بالدقائق','فترة الكارت المكتملة بالدقائق',...branches.map(([,name])=>name+' بالدقائق'),'إضافي','خارج الفروع','فجوات GPS','دقائق التأخير','مرات الخروج','مصدر الحضور','ينقص انصراف الكارت','دقائق مبدئية غير معتمدة'],...reports.flatMap(r=>r.days.map(d=>[r.user.name,r.user.username,d.date,({present:'حاضر',absent:'غائب',off:'راحة أسبوعية',pending:'الشيفت لم ينتهِ',upcoming:'لم يبدأ الشيفت',unverified:'حضور غير مؤكد',untracked:'خارج فترة المتابعة'} as Record<string,string>)[d.status],d.policy.shift_start,d.policy.shift_end,d.firstArrival,d.lastDeparture,d.summary.totalMinutes,d.summary.cardMinutes,...branches.map(([id])=>d.summary.branches.find(b=>b.id===id)?.minutes||0),d.summary.overtimeMinutes,d.summary.outsideMinutes,d.summary.unknownMinutes,d.lateMinutes,d.exitCount,d.attendanceSource,d.missingCheckout?'نعم':'لا',d.provisionalMinutes]))]:
    [['الموظف','اسم الدخول','من','إلى','أيام العمل حتى الآن','أيام الحضور','أيام الغياب','أيام الراحة','أيام التأخير','التأخير بالدقائق','داخل الفروع حسب GPS بالدقائق','فترة الكارت المكتملة بالدقائق',...branches.map(([,name])=>name+' بالدقائق'),'خلال الشيفت','إضافي','خارج الفروع','فجوات GPS','مرات الخروج','انصراف مبكر','أيام ينقصها انصراف','دقائق مبدئية غير معتمدة'],...reports.map(r=>[r.user.name,r.user.username,r.start,r.end,r.summary.scheduledDays,r.summary.presentDays,r.summary.absentDays,r.summary.offDays,r.summary.lateDays,r.summary.late.minutes,r.summary.total.minutes,r.summary.card.minutes,...branches.map(([id])=>r.summary.branches.find(b=>b.id===id)?.minutes||0),r.summary.regular.minutes,r.summary.overtime.minutes,r.summary.outside.minutes,r.summary.unknown.minutes,r.summary.exitCount,r.summary.earlyDeparture.minutes,r.summary.missingCheckoutDays,r.summary.provisional.minutes])];
  const bleBranches=[...new Map(reports.flatMap(r=>(r.ble_branches||[]).map(b=>[b.id,b.name] as const))).entries()];
  rows[0].push('رصد BLE متاح','التاج مرصود بالدقائق','التاج غير مرصود بالدقائق','فجوات BLE بالدقائق','فترة متابعة الكارت BLE بالدقائق',...bleBranches.map(([,name])=>'رصد BLE في '+name+' بالدقائق'),'بيانات BLE محدودة');
  const targets=details?reports.flatMap(r=>r.days):reports;
  const minutes=(seconds:number|undefined)=>Math.round((seconds||0)/60*100)/100;
  targets.forEach((r,i)=>rows[i+1].push(r.ble_has_history?'نعم':'لا',
    ...['observed_seconds','not_seen_seconds','unknown_seconds','session_seconds'].map(key=>r.ble_has_history?minutes(r.ble_summary?.[key as keyof NonNullable<typeof r.ble_summary>]):''),
    ...bleBranches.map(([id])=>r.ble_has_history?minutes(r.ble_branches?.find(b=>b.id===id)?.observed_seconds):''),r.ble_truncated?'نعم':'لا'));
  const quote=(value:unknown)=>'"'+String(value??'').replace(/^(\s*)([=+@-])/,"'$1$2").replaceAll('"','""')+'"';
  return '\uFEFF'+rows.map(row=>row.map(quote).join(',')).join('\r\n');
}
