'use client';
import {useEffect,useState} from 'react';
import type {AttendanceReport} from '@/lib/attendance';
import type {BleReportFields} from '@/lib/ble-types';
type Row=AttendanceReport&BleReportFields&{user:{id:number;name:string;username:string};dayEnded:boolean;places:{id:string;name:string;formatted:string;percentage:number}[]};
function bleTime(seconds=0){return `${Math.floor(seconds/3600)} ساعة ${Math.floor(seconds%3600/60)} دقيقة`}
export default function DayCloseReport(){
  const [date,setDate]=useState(''),[data,setData]=useState<{businessDay:string;boundary:string;generatedAt:string;reports:Row[]}|null>(null),[error,setError]=useState('');
  useEffect(()=>{const c=new AbortController();const load=async()=>{try{const r=await fetch('/api/attendance/day-close'+(date?'?date='+date:''),{cache:'no-store',signal:c.signal});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){if(!c.signal.aborted)setError((e as Error).message);}};void load();const t=setInterval(()=>void load(),60000);return()=>{c.abort();clearInterval(t);};},[date]);
  return <section className="card"><h3>تقرير نهاية يوم العمل — كل الموظفين</h3><p className="muted">يظهر آخر يوم عمل انتهى تلقائيًا، ويُحدّث من السجلات الفعلية كل دقيقة أثناء فتح الصفحة. القراءات المتأخرة والمراجعات تحدّث التقرير. رصد التاج يظهر منفصلًا عن GPS. الوقت غير المرصود وفجوات القارئ يحتاجان مراجعة ولا يتحولان إلى خصم تلقائي.</p><label>اختيار يوم عمل<input type="date" className="form-input" value={date||data?.businessDay||''} onChange={e=>setDate(e.target.value)}/></label><button className="btn btn-secondary" onClick={()=>setDate('')}>آخر يوم انتهى تلقائيًا</button>{error&&<p role="alert">{error}</p>}{data&&<><p>يوم {data.businessDay} · يبدأ الساعة {data.boundary} بتوقيت القاهرة</p><div className="data-table-wrapper"><table className="data-table"><thead><tr><th>الموظف</th><th>حضور / انصراف الكارت</th><th>فترة الكارت المكتملة</th><th>داخل الفروع حسب GPS</th><th>خارج الفروع</th><th>غير معلوم</th><th>توزيع الأماكن</th><th>التاج مرصود</th><th>التاج غير مرصود</th><th>رصد غير معلوم</th><th>مراجعة</th></tr></thead><tbody>{data.reports.map(r=><tr key={r.user.id}><td>{r.user.name}</td><td>{r.firstArrival?new Date(r.firstArrival).toLocaleString('ar-EG',{timeZone:'Africa/Cairo'}):'لا يوجد حضور'}<br/>{r.lastDeparture?new Date(r.lastDeparture).toLocaleString('ar-EG',{timeZone:'Africa/Cairo'}):'لا يوجد انصراف'}</td><td>{r.summary.cardFormatted}{r.provisionalMinutes>0&&<small> · فترة مفتوحة {r.provisionalMinutes} دقيقة</small>}</td><td>{r.summary.totalFormatted}</td><td style={{color:'#b91c1c',fontWeight:700}}>{r.summary.outsideFormatted}</td><td>{r.summary.unknownFormatted}</td><td>{r.places.map(p=><div key={p.id}>{p.name}: {p.formatted} ({p.percentage}%)</div>)}</td><td>{r.ble_has_history?bleTime(r.ble_summary?.observed_seconds):'—'}</td><td style={{color:'#b91c1c',fontWeight:700}}>{r.ble_has_history?bleTime(r.ble_summary?.not_seen_seconds):'—'}</td><td>{r.ble_has_history?bleTime(r.ble_summary?.unknown_seconds):'—'}{r.ble_truncated?' · بيانات محدودة':''}</td><td>{r.missingCheckout?'انصراف ناقص':r.missingArrival?'حضور ناقص':!r.firstArrival?'لم يسجل حضورًا':r.ble_has_history&&(r.ble_summary?.not_seen_seconds||r.ble_summary?.unknown_seconds)?'تحتاج مراجعة رصد التاج':r.summary.unknownMinutes||r.summary.outsideMinutes?'تحتاج مراجعة GPS':'—'}</td></tr>)}</tbody></table></div></>}</section>;
}
