'use client';
import {useCallback,useEffect,useState} from 'react';
import type {AppUser} from '@/lib/types';
import {localDate} from '@/lib/time';
interface Device{id:string;name:string;branch_id:string;is_active:boolean;last_seen_at:string|null}
interface Card{id:number;uid:string;user_id:number;name:string}
interface Scan{id:string;card_uid:string;user_id:number|null;user_name:string|null;device_name:string;branch_id:string;recorded_at:string|null;received_at:string;status:string;event_type:string|null;shift_day:string|null;review_note:string|null}
interface ReviewAudit {id:string;admin_name:string;created_at:string;note:string;previous_data:{event_type:string|null;shift_day:string|null};new_data:{event_type:string|null;shift_day:string|null}}
interface Data{devices:Device[];cards:Card[];scans:Scan[];total:number;branches:{id:string;name:string}[]}
const labels:Record<string,string>={rapid_repeat:'إعادة مسح سريعة / Refresh',after_checkout:'Refresh بعد الانصراف',before_open:'قبل فتح الحضور',manual_conflict:'تعارض مع مراجعة المدير',pending:'انتظار التصنيف',accepted:'محفوظة',duplicate_action:'قراءة إضافية لنفس الحركة',unknown_card:'كارت غير مربوط',outside_window:'خارج نوافذ الشيفت',ambiguous_window:'نوافذ متداخلة',invalid_time:'ساعة الجهاز تحتاج مراجعة',before_start:'قبل بداية السجل',inactive_user:'حساب معطّل أو ليس موظفًا',ignored:'تجاهلها المدير'};
export default function NfcManager({users}:{users:AppUser[]}){
  const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[page,setPage]=useState(1),[reviewOnly,setReviewOnly]=useState(false),[audit,setAudit]=useState<ReviewAudit[]>([]);
  const [deviceName,setDeviceName]=useState(''),[branch,setBranch]=useState('branch1'),[uid,setUid]=useState(''),[employee,setEmployee]=useState('');
  const [secret,setSecret]=useState<{device_id:string;token:string}|null>(null),[selected,setSelected]=useState<Scan|null>(null);
  const [review,setReview]=useState({user_id:'',event_type:'clock_in',shift_day:localDate(),recorded_at:'',note:''});
  const load=useCallback(async()=>{try{const r=await fetch(`/api/nfc/admin?page=${page}&review=${reviewOnly}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setError('');}catch(e){setError((e as Error).message);}},[page,reviewOnly]);
  useEffect(()=>{queueMicrotask(()=>void load());const t=setInterval(()=>void load(),15000);return()=>clearInterval(t);},[load]);
  const action=async(body:Record<string,unknown>)=>{setBusy(true);setError('');try{const r=await fetch('/api/nfc/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);await load();return d;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}};
  const time=(v:string|null)=>v?new Date(v).toLocaleString('ar-EG',{timeZone:'Africa/Cairo'}):'توقيت غير معلوم';
  return <section className="attendance-reports"><div className="card"><h3>الكروت وقارئات الفروع</h3><p className="muted">كل فرع: قارئ RC522 + ESP32 + Wi‑Fi. كل قراءة تُحفظ بوقت التقاطها ووقت وصولها. الحضور والانصراف بالكارت؛ GPS بين الحضور والانصراف للتحقق من الوجود، ويتوقف عند الحد الأقصى إذا نقص الانصراف.</p><p className="muted">أول قراءة في يوم العمل حضور؛ التالية Refresh حتى فتح الانصراف. الكارت وحده لا يثبت وجود الموظف، والموقع غير المتاح يظهر فجوة تتبع.</p>
    <form onSubmit={async e=>{e.preventDefault();const result=await action({action:'create_device',name:deviceName,branch_id:branch});if(result){setSecret(result);setDeviceName('');}}}><div className="report-filters"><label>اسم القارئ<input className="form-input" value={deviceName} onChange={e=>setDeviceName(e.target.value)} required maxLength={100}/></label><label>فرع القارئ<select className="form-input" value={branch} onChange={e=>setBranch(e.target.value)}>{data?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><button className="btn btn-primary" disabled={busy}>إضافة قارئ وإصدار مفتاحه</button></form>
    {secret&&<div className="tracker-warning"><h4>إعداد القارئ — المفتاح يظهر مرة واحدة</h4><p>انسخ القيم إلى attendance-config.h على ESP32. المفتاح خاص بهذا القارئ؛ لا تشاركه مع الموظفين.</p><label>DEVICE_ID<input className="form-input" readOnly value={secret.device_id}/></label><label>DEVICE_TOKEN<input className="form-input" readOnly type="password" value={secret.token}/></label><button className="btn btn-secondary" onClick={()=>void navigator.clipboard.writeText(`DEVICE_ID=${secret.device_id}\nDEVICE_TOKEN=${secret.token}`)}>نسخ إعدادات القارئ</button><button className="btn btn-secondary" onClick={()=>setSecret(null)}>إخفاء</button></div>}
    {data?.devices.map(d=><div className="movement-row" key={d.id}><div><strong>{d.name}</strong><p>{data.branches.find(b=>b.id===d.branch_id)?.name||d.branch_id} · {d.is_active?'مفعّل':'معطّل'} · آخر اتصال: {d.last_seen_at?time(d.last_seen_at):'لم يتصل بعد'}</p></div><div><button className="btn btn-secondary btn-sm" disabled={busy} onClick={()=>void action({action:'device_active',id:d.id,is_active:!d.is_active})}>{d.is_active?'تعطيل':'تفعيل'}</button><button className="btn btn-secondary btn-sm" disabled={busy} onClick={async()=>{const r=await action({action:'rotate_device',id:d.id});if(r)setSecret(r);}}>إصدار مفتاح بديل</button></div></div>)}
  </div><div className="card"><h3>ربط كارت بموظف</h3><p className="muted">مرّر الكارت أولًا، انسخ رقمه من سجل القراءات، ثم اربطه بالموظف. الربط يبدأ من وقت الحفظ؛ القراءة الأولى تظل للمراجعة ويمكن اعتمادها يدويًا.</p><form onSubmit={async e=>{e.preventDefault();const r=await action({action:'assign_card',uid,user_id:Number(employee)});if(r)setUid('');}}><div className="report-filters"><label>رقم الكارت UID<input className="form-input" value={uid} onChange={e=>setUid(e.target.value)} required placeholder="مثال: 0F12345678"/></label><label>الموظف<select className="form-input" value={employee} onChange={e=>setEmployee(e.target.value)} required><option value="">اختر الموظف</option>{users.filter(u=>u.role==='employee'&&u.is_active!==false).map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label></div><button className="btn btn-primary" disabled={busy}>ربط الكارت</button></form>{data?.cards.map(c=><div className="movement-row" key={c.id}><span>{c.name} · <code>{c.uid}</code></span><button className="btn btn-secondary btn-sm" disabled={busy} onClick={()=>void action({action:'revoke_card',id:c.id})}>إلغاء الربط / كارت مفقود</button></div>)}</div>
    <div className="card"><div className="section-title"><h3>كل قراءات الكروت</h3><button className="btn btn-secondary" onClick={()=>void load()}>تحديث</button></div><label><input type="checkbox" checked={reviewOnly} onChange={e=>{setReviewOnly(e.target.checked);setPage(1);}}/> قراءات تحتاج مراجعة فقط</label>{error&&<p role="alert" className="tracker-warning">{error}</p>}<div className="data-table-wrapper"><table className="data-table"><thead><tr><th>الموظف / الكارت</th><th>القارئ</th><th>وقت القراءة</th><th>وصل للسيرفر</th><th>الحركة</th><th>الحالة</th><th>الإدارة</th></tr></thead><tbody>{data?.scans.map(s=><tr key={s.id}><td>{s.user_name||'غير مربوط'}<br/><code>{s.card_uid}</code></td><td>{s.device_name}</td><td>{time(s.recorded_at)}</td><td>{time(s.received_at)}</td><td>{s.event_type==='clock_in'?'حضور':s.event_type==='clock_out'?'انصراف':s.event_type==='refresh'?'حركة / Refresh':'—'}<br/>{s.shift_day}</td><td>{labels[s.status]||s.status}{s.review_note&&<p>{s.review_note}</p>}</td><td><button className="btn btn-secondary btn-sm" onClick={()=>{setSelected(s);setAudit([]);void fetch('/api/nfc/admin?scanId='+s.id).then(r=>r.json()).then(d=>setAudit(d.history||[]));setReview({user_id:String(s.user_id||''),event_type:s.event_type||'clock_in',shift_day:s.shift_day||localDate(),recorded_at:s.recorded_at||'',note:''});}}>مراجعة</button><button className="btn btn-secondary btn-sm" onClick={()=>setUid(s.card_uid)}>استخدام رقم الكارت</button></td></tr>)}</tbody></table></div>{data&&!data.scans.length&&<p>لا توجد قراءات في السجل.</p>}<div className="report-actions"><button className="btn btn-secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>السابق</button><span>صفحة {page} · {data?.total||0} قراءة</span><button className="btn btn-secondary" disabled={page*100>=(data?.total||0)} onClick={()=>setPage(p=>p+1)}>التالي</button></div></div>
    {selected&&<div className="modal-overlay"><section className="modal employee-editor" role="dialog" aria-modal="true" aria-labelledby="scan-review-title"><h3 id="scan-review-title">مراجعة قراءة {selected.card_uid}</h3>{audit.length>0&&<details><summary>تاريخ تعديلات القراءة</summary>{audit.map(a=><p key={a.id}>{a.admin_name} · {time(a.created_at)} · {a.note}<br/>{a.previous_data.event_type||'غير مصنفة'} → {a.new_data.event_type||'تجاهل'} · {a.new_data.shift_day}</p>)}</details>}<form onSubmit={async e=>{e.preventDefault();const r=await action({action:'review_scan',id:selected.id,...review,user_id:Number(review.user_id),...(review.recorded_at?{recorded_at:review.recorded_at}:{})});if(r)setSelected(null);}}><div className="report-filters"><label>الموظف<select className="form-input" value={review.user_id} onChange={e=>setReview({...review,user_id:e.target.value})} required={review.event_type!=='ignored'}><option value="">اختر الموظف</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label>نوع القراءة<select className="form-input" value={review.event_type} onChange={e=>setReview({...review,event_type:e.target.value})}><option value="clock_in">حضور</option><option value="clock_out">انصراف</option><option value="ignored">تجاهل القراءة</option></select></label><label>يوم بداية الشيفت<input className="form-input" type="date" value={review.shift_day} onChange={e=>setReview({...review,shift_day:e.target.value})}/></label><label>وقت القراءة UTC (لتصحيح الساعة)<input className="form-input" value={review.recorded_at} placeholder="2026-10-03T09:00:00Z" onChange={e=>setReview({...review,recorded_at:e.target.value})}/></label><label>سبب التعديل<input className="form-input" required maxLength={1000} value={review.note} onChange={e=>setReview({...review,note:e.target.value})}/></label></div><p className="muted">التعديل يحدّث التقرير ويحفظ من عدّله والسبب في سجل مراجعة خاص. لتغيير حضور معتمد بديلًا عن قراءة أخرى، تجاهل القراءة القديمة أولًا.</p>{error&&<p role="alert">{error}</p>}<div className="report-actions"><button className="btn btn-primary" disabled={busy}>اعتماد التعديل</button><button type="button" className="btn btn-secondary" onClick={()=>setSelected(null)}>إغلاق</button></div></form></section></div>}
  </section>;
}
